global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "service-discovery"
    static_configs:
      - targets: ["service_discovery:8500"]
    metrics_path: /metrics
    scheme: http

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
